export const aliasesAnimals: Record<string, string[]> = {
    ant: ['insect', 'bug', 'small', 'work'],
    bat: ['animal', 'night', 'flying', 'halloween'],
    bear: ['animal', 'nature', 'wild', 'teddy'],
    bee: ['insect', 'nature', 'honey', 'work'],
    bug: ['insect', 'error', 'debug', 'issue', 'defect', 'beetle'],
    bunny: ['rabbit', 'animal', 'easter', 'nature'],
    butterfly: ['insect', 'nature', 'beauty', 'transform'],
    cat: ['animal', 'pet', 'feline'],
    caterpillar: ['insect', 'larva', 'nature', 'growth'],
    chicken: ['animal', 'meat', 'farm', 'food', 'poultry'],
    cow: ['animal', 'farm', 'milk', 'livestock'],
    dinosaur: ['animal', 'extinct', 'ancient', 'old'],
    dog: ['animal', 'pet', 'canine', 'friend'],
    dolphin: ['animal', 'ocean', 'sea', 'swim', 'intelligent'],
    dragon: ['fantasy', 'myth', 'fire', 'monster', 'legend'],
    duck: ['animal', 'bird', 'pond', 'water', 'quack'],
    elephant: ['animal', 'big', 'nature', 'trunk', 'safari'],
    fish: ['animal', 'ocean', 'sea', 'food', 'swimming'],
    goat: ['animal', 'farm', 'greatest', 'mountain'],
    monkey: ['animal', 'primate', 'jungle', 'ape', 'banana', 'wildlife'],
    mouse: ['animal', 'peripheral', 'computer', 'input'],
    penguin: ['animal', 'cold', 'bird', 'arctic', 'linux'],
    pig: ['animal', 'farm', 'pink', 'pork', 'bacon'],
    snake: ['animal', 'reptile', 'danger', 'poison', 'slither'],
    turkey: ['animal', 'bird', 'thanksgiving', 'meat', 'farm'],
    turtle: ['animal', 'reptile', 'slow', 'shell', 'sea'],
};
