export const aliasesDevices: Record<string, string[]> = {
    appliances: ['devices', 'home', 'electronics', 'kitchen'],
    'button-device': ['iot', 'switch', 'remote', 'control', 'smart', 'wireless', 'push'],
    camera: ['photo', 'picture', 'image', 'snapshot', 'photography'],
    cpu: ['processor', 'hardware', 'chip', 'system', 'compute'],
    devices: ['hardware', 'electronics', 'gadgets', 'equipment'],
    dishwasher: ['appliance', 'kitchen', 'clean', 'dishes'],
    'drying-machine': ['dryer', 'appliance', 'laundry', 'clothes'],
    fan: ['cooling', 'ventilation', 'air', 'blade', 'rotate', 'appliance'],
    fridge: ['refrigerator', 'appliance', 'kitchen', 'cold', 'storage'],
    'gas-detector': ['sensor', 'safety', 'alarm', 'gas', 'leak'],
    gateway: ['router', 'hub', 'bridge', 'network', 'connection'],
    headphones: ['audio', 'music', 'listen', 'sound'],
    'ir-emitter': ['infrared', 'remote', 'control', 'signal', 'wireless'],
    joystick: ['game', 'controller', 'play', 'console', 'gaming'],
    'light-bulb': ['lamp', 'light', 'idea', 'brightness', 'illumination'],
    'light-switch': ['switch', 'toggle', 'light', 'control', 'on-off'],
    microphone: ['audio', 'record', 'voice', 'mic', 'sound', 'speak', 'input'],
    microwave: ['appliance', 'heating', 'kitchen', 'oven', 'quick-cook'],
    monitor: ['screen', 'display', 'watch', 'view', 'track'],
    motion: ['movement', 'sensor', 'activity', 'detection'],
    nas: ['storage', 'network', 'server', 'drive', 'backup'],
    phone: ['call', 'mobile', 'contact', 'communication'],
    plug: ['power', 'socket', 'outlet', 'electricity', 'connect'],
    printer: ['print', 'paper', 'document', 'output'],
    purifier: ['air', 'clean', 'filter', 'quality'],
    raspberry: ['pi', 'fruit', 'berry', 'iot', 'hardware'],
    robot: ['ai', 'bot', 'automation', 'tech'],
    router: ['network', 'wifi', 'internet', 'gateway'],
    satellite: ['space', 'communication', 'orbit', 'signal'],
    smartphone: ['phone', 'mobile', 'device', 'cell'],
    smb: ['server', 'shared', 'samba', 'nas', 'storage'],
    'smoke-detector': ['sensor', 'safety', 'alarm', 'smoke', 'fire'],
    speaker: ['sound', 'audio', 'volume', 'music'],
    tv: ['television', 'screen', 'video', 'display'],
    upnp: ['plug-and-play', 'streaming', 'discovery', 'device'],
    vacuum: ['cleaner', 'appliance', 'cleaning'],
    'washing-machine': ['washer', 'appliance', 'laundry', 'clothes'],
    'water-leak': ['water', 'leak', 'sensor', 'safety', 'flood'],
    'air-conditioning': ['ac', 'air', 'aircon', 'climate', 'cooling', 'hvac', 'heat-pump', 'ventilation'],
    digital: ['electronic', 'tech', 'binary', 'screen', 'device', 'computing', 'online'],
};
