export const aliasesFiletypes: Record<string, string[]> = {
    'filetype-avi': ['filetype', 'avi'],
    'filetype-bat': ['filetype', 'bat'],
    'filetype-c': ['filetype', 'c'],
    'filetype-css': ['filetype', 'css'],
    'filetype-csv': ['filetype', 'csv'],
    'filetype-doc': ['filetype', 'doc'],
    'filetype-docx': ['filetype', 'docx'],
    'filetype-gif': ['filetype', 'gif'],
    'filetype-html': ['filetype', 'html'],
    'filetype-ico': ['filetype', 'ico'],
    'filetype-ini': ['filetype', 'ini'],
    'filetype-javascript': ['filetype', 'javascript'],
    'filetype-jpeg': ['filetype', 'jpeg'],
    'filetype-jpg': ['filetype', 'jpg'],
    'filetype-json': ['filetype', 'json'],
    'filetype-less': ['filetype', 'less'],
    'filetype-mp3': ['filetype', 'mp3'],
    'filetype-mp4': ['filetype', 'mp4'],
    'filetype-mpg': ['filetype', 'mpg'],
    'filetype-php': ['filetype', 'php'],
    'filetype-png': ['filetype', 'png'],
    'filetype-ppt': ['filetype', 'ppt'],
    'filetype-psd': ['filetype', 'psd'],
    'filetype-rar': ['filetype', 'rar'],
    'filetype-sass': ['filetype', 'sass'],
    'filetype-sql': ['filetype', 'sql'],
    'filetype-tiff': ['filetype', 'tiff'],
    'filetype-txt': ['filetype', 'txt'],
    'filetype-typescript': ['code', 'programming', 'js', 'script', 'type-safe', 'ts'],
    'filetype-wav': ['filetype', 'wav'],
    'filetype-xls': ['filetype', 'xls'],
    'filetype-xlsx': ['filetype', 'xlsx'],
    'filetype-zip': ['filetype', 'zip'],
};
