export const aliasesFood: Record<string, string[]> = {
    avocado: ['fruit', 'healthy', 'fat', 'green', 'guacamole'],
    banana: ['fruit', 'yellow', 'potassium', 'snack'],
    beans: ['food', 'legume', 'coffee', 'source'],
    beer: ['alcohol', 'drink', 'bar', 'party', 'pub'],
    'birthday-cake': ['celebration', 'party', 'cake', 'birthday', 'anniversary'],
    blueberries: ['fruit', 'berry', 'antioxidant', 'blue', 'healthy'],
    bread: ['bakery', 'food', 'wheat', 'carbs', 'toast'],
    breakfast: ['meal', 'morning', 'food', 'eat'],
    cake: ['dessert', 'birthday', 'celebration', 'sweet'],
    candy: ['sweet', 'sugar', 'treat', 'snack'],
    carrot: ['vegetable', 'food', 'healthy', 'diet'],
    cheese: ['dairy', 'food', 'yellow', 'slice', 'pizza'],
    cherries: ['fruit', 'berry', 'red', 'sweet'],
    chestnut: ['roasted', 'nut', 'autumn', 'brown', 'conker'],
    chocolate: ['sweet', 'dessert', 'sugar', 'treat', 'cocoa'],
    coffee: ['drink', 'caffeine', 'mug', 'cup', 'break', 'cafe', 'morning', 'energy'],
    cook: ['chef', 'cooking', 'kitchen', 'recipe', 'prepare', 'meal', 'food'],
    cookies: ['biscuits', 'baked', 'chocolate-chip', 'crunchy', 'dough'],
    corn: ['vegetable', 'farm', 'yellow', 'maize', 'food'],
    cucumber: ['vegetable', 'green', 'fresh', 'salad', 'healthy'],
    dessert: ['sweet', 'confectionery', 'pastry', 'treat', 'sugar'],
    dinner: ['meal', 'evening', 'food', 'eat', 'supper'],
    egg: ['breakfast', 'food', 'protein', 'chicken', 'oval'],
    eggplant: ['vegetable', 'purple', 'aubergine', 'food'],
    fondue: ['cheese', 'chocolate', 'melted', 'dipping', 'pot'],
    food: ['meal', 'eat', 'nutrition', 'diet'],
    'french-fries': ['fast-food', 'potato', 'snack', 'salty', 'junk-food'],
    fruits: ['apple', 'food', 'organic', 'groceries', 'citrus', 'berries', 'tropical'],
    glass: ['transparent', 'crystal', 'fragile', 'window', 'cup'],
    'ice-cream': ['dessert', 'cold', 'sweet', 'summer', 'gelato'],
    ingredients: ['recipe', 'items', 'food', 'shopping', 'grocery', 'checklist', 'nutrition'],
    knife: ['tool', 'cut', 'kitchen', 'weapon', 'sharp'],
    lemon: ['fruit', 'sour', 'citrus', 'yellow', 'acid'],
    lollipop: ['candy', 'sweet', 'treat', 'child'],
    lunch: ['meal', 'midday', 'food', 'eat'],
    meat: ['food', 'protein', 'beef', 'pork', 'steak', 'butcher'],
    melon: ['fruit', 'summer', 'sweet', 'watery', 'green'],
    milk: ['dairy', 'drink', 'white', 'calcium', 'cow'],
    mushroom: ['nature', 'fungi', 'forest', 'food', 'poisonous'],
    olives: ['mediterranean', 'oil', 'appetizer', 'pickled', 'green', 'black'],
    peanut: ['legume', 'butter', 'protein', 'shell', 'salty'],
    pear: ['fruit', 'food', 'healthy'],
    pepper: ['vegetable', 'spicy', 'hot', 'chili', 'seasoning'],
    pizza: ['food', 'italian', 'slice', 'fast-food', 'cheese'],
    polenta: ['cornmeal', 'maize', 'porridge', 'boiled', 'yellow', 'side-dish'],
    popcorn: ['movie', 'cinema', 'snack', 'entertainment'],
    potato: ['vegetable', 'root', 'food', 'carbs', 'earth'],
    pudding: ['custard', 'creamy', 'dessert', 'sweet', 'snack'],
    rice: ['food', 'grain', 'asian', 'carbs', 'white'],
    salad: ['food', 'healthy', 'vegetables', 'green', 'diet'],
    salt: ['sodium', 'nutrition', 'food', 'seasoning'],
    'soft-drink': ['soda', 'beverage', 'carbonated', 'refreshment', 'cola'],
    soup: ['broth', 'liquid', 'bowl', 'hot', 'stew', 'dinner'],
    strawberry: ['fruit', 'berry', 'red', 'sweet', 'summer'],
    sugar: ['sweet', 'nutrition', 'food', 'carbs'],
    tomato: ['vegetable', 'red', 'garden', 'ketchup', 'salad'],
    vegetables: ['carrot', 'greens', 'plant', 'organic', 'groceries', 'salad', 'vegan', 'fresh'],
};
