export const aliasesHealth: Record<string, string[]> = {
    blood: ['medical', 'health', 'emergency', 'donor', 'red'],
    bones: ['skeleton', 'orthopedic', 'bone', 'fracture', 'skeletal', 'osteo'],
    brain: ['neurology', 'mind', 'cerebral', 'cognition', 'head', 'thinking'],
    dental: ['tooth', 'teeth', 'dentist', 'oral', 'mouth', 'molar'],
    digestive: ['stomach', 'gastro', 'gut', 'intestine', 'gastrointestinal', 'belly'],
    doctor: ['medical', 'health', 'physician', 'medicine', 'hospital'],
    ears: ['hearing', 'audio', 'ent', 'auditory', 'otology', 'listen'],
    endocrine: ['thyroid', 'hormones', 'glands', 'metabolism', 'pituitary'],
    heart: ['love', 'like', 'favorite', 'health', 'cardio'],
    hospital: ['medical', 'health', 'doctor', 'emergency', 'clinic'],
    laboratory: ['lab', 'test', 'beaker', 'experiment', 'science', 'analysis'],
    liver: ['organ', 'hepatic', 'health', 'medical', 'anatomy'],
    lungs: ['respiratory', 'pulmonary', 'breathing', 'organ', 'chest', 'respiration'],
    mental: ['mind', 'psychology', 'mental health', 'brain', 'psychiatric', 'wellness'],
    nervous: ['neurology', 'nervous system', 'neural', 'nerves', 'neuro', 'brain'],
    nose: ['ent', 'nasal', 'olfactory', 'smell', 'respiration', 'sinus'],
    pharmacy: ['medicine', 'drugs', 'health', 'clinic'],
    pill: ['medical', 'medicine', 'drug', 'pharmacy', 'health'],
    prescription: ['medication', 'medical', 'drugs', 'rx', 'pharmacy', 'treatment'],
    referral: ['reference', 'transfer', 'send', 'redirect', 'patient', 'doctor'],
    reproductive: ['fertility', 'obstetric', 'gynecology', 'medical', 'pregnancy'],
    skin: ['dermatology', 'epidermis', 'dermal', 'health', 'medical', 'texture'],
    skull: ['danger', 'death', 'dead', 'poison', 'skeleton'],
    stethoscope: ['doctor', 'medical', 'health', 'heartbeat', 'diagnosis', 'clinic'],
    surgery: ['medical', 'operation', 'hospital', 'scalpel'],
    teeth: ['dentist', 'medical', 'oral', 'health'],
    thermometer: ['temperature', 'heat', 'cold', 'weather'],
};
