export const aliasesMedia: Record<string, string[]> = {
    'cd-dvd': ['media', 'disc', 'storage', 'music', 'video', 'retro'],
    equalizer: ['audio', 'mixer', 'sound', 'frequency', 'sliders', 'bass'],
    gallery: ['photo', 'media', 'album', 'lightbox', 'grid', 'image', 'slideshow', 'collection', 'portfolio', 'thumbnails', 'snapshots', 'snapshots'],
    hd: ['quality', 'video', 'resolution', 'high-definition'],
    image: ['photo', 'picture', 'frame', 'gallery', 'visual', 'media', 'artwork', 'slideshow'],
    movie: ['film', 'video', 'cinema', 'play', 'watch'],
    'musical-note': ['audio', 'melody', 'song', 'tune'],
    mute: ['silent', 'quiet', 'sound-off', 'volume'],
    pause: ['stop', 'hold', 'wait', 'suspend'],
    play: ['start', 'run', 'begin', 'video', 'media'],
    radio: ['audio', 'music', 'broadcast', 'news', 'old-school'],
    reload: ['refresh', 'update', 'sync', 'restart'],
    repeat: ['loop', 'cycle', 'again', 'replay'],
    sd: ['quality', 'video', 'resolution', 'standard-definition'],
    shuffle: ['random', 'mix', 'randomize', 'crossing', 'arrows', 'playback'],
    stop: ['halt', 'end', 'terminate', 'finish'],
    'stop-sign': ['halt', 'warning', 'caution', 'stop'],
    streaming: ['video', 'live', 'broadcast', 'media'],
    theater: ['cinema', 'performance', 'stage', 'drama', 'acting'],
    unmute: ['sound', 'volume', 'audio', 'on'],
    video: ['camera', 'recording', 'film', 'media'],
    youtube: ['video', 'streaming', 'channel', 'play', 'social', 'media', 'creator', 'watch'],
};
