export const aliasesNavigation: Record<string, string[]> = {
    'arrow-down': ['down', 'arrow', 'direction', 'below', 'south'],
    'arrow-left': ['arrow', 'back', 'previous', 'west', 'direction'],
    'arrow-right': ['arrow', 'forward', 'next', 'east', 'direction'],
    'arrow-up': ['up', 'arrow', 'direction', 'above', 'north'],
    'arrow-bidirectional-horizontal': ['resize', 'expand', 'left-right', 'width', 'horizontal', 'stretch'],
    'arrow-bidirectional-vertical': ['resize', 'expand', 'up-down', 'height', 'sort', 'vertical'],
    brightness: ['light', 'display', 'screen', 'intensity', 'dimmer', 'sun'],
    'caret-down': ['arrow', 'below', 'bottom', 'decrease'],
    'caret-left': ['arrow', 'back', 'previous', 'collapse'],
    'caret-right': ['arrow', 'next', 'forward', 'expand'],
    'caret-up': ['arrow', 'above', 'top', 'increase'],
    categories: ['organize', 'groups', 'classification', 'tags', 'folder'],
    checkmark: ['check', 'done', 'complete', 'success', 'yes', 'confirm', 'tick'],
    clear: ['cancel', 'close', 'remove', 'dismiss', 'exit'],
    context: ['menu', 'options', 'settings', 'more', 'dots'],
    'deselect-all': ['uncheck', 'clear', 'none', 'unselect'],
    edit: ['modify', 'change', 'update', 'pencil', 'write'],
    enlarge: ['expand', 'maximize', 'fullscreen', 'grow', 'increase', 'zoom in', 'scale up'],
    filters: ['filter', 'sort', 'refine', 'criteria', 'narrow', 'funnel', 'query'],
    grid: ['layout', 'tiles', 'view', 'display', 'matrix'],
    group: ['combine', 'folder', 'collection', 'cluster', 'batch', 'organize'],
    layers: ['all', 'stack', 'overlay', 'depth', 'sheets', 'overlap', 'levels'],
    list: ['menu', 'items', 'lines', 'rows', 'view'],
    'menu-hamburger': ['menu', 'navigation', 'nav', 'sidebar', 'drawer', 'burger', 'toggle', 'options', 'more', 'expand'],
    minus: ['subtract', 'remove', 'less', 'decrease', 'negative'],
    next: ['forward', 'arrow', 'continue', 'advance'],
    plus: ['add', 'new', 'create', 'increase', 'positive'],
    previous: ['back', 'arrow', 'before', 'prior'],
    return: ['back', 'undo', 'arrow', 'revert'],
    search: ['find', 'lookup', 'query', 'magnify', 'explore'],
    shrink: ['collapse', 'minimize', 'compress', 'reduce', 'decrease', 'zoom out', 'scale down'],
    square: ['shape', 'rectangle', 'box', 'outline', 'geometry', 'border'],
    table: ['grid', 'data', 'rows', 'columns', 'list'],
    tune: ['filter', 'filters', 'sliders', 'adjust', 'settings', 'controls', 'refine', 'options'],
    ungroup: ['separate', 'split', 'detach', 'break-apart', 'release', 'expand'],
    'vertical-dots': ['menu', 'more', 'options', 'kebab'],
    view: ['eye', 'see', 'show', 'display', 'preview', 'look'],
};
