export const aliasesPlaces: Record<string, string[]> = {
    bank: ['finance', 'institution', 'building', 'account', 'wire-transfer'],
    bath: ['hygiene', 'bathroom', 'shower', 'relax', 'clean'],
    bed: ['sleep', 'rest', 'hotel', 'accommodation'],
    building: ['office', 'company', 'organization', 'headquarters', 'facility', 'site', 'location', 'property', 'realestate', 'enterprise', 'workplace', 'commercial'],
    door: ['entrance', 'exit', 'access', 'entry'],
    home: ['house', 'main', 'dashboard', 'start'],
    lantern: ['light', 'dark', 'lamp', 'camping', 'outdoor'],
    rooms: ['locations', 'spaces', 'areas', 'places'],
    school: ['education', 'learn', 'building', 'class', 'students'],
    basement: ['cellar', 'underground', 'lower-floor', 'storage', 'crawlspace', 'sublevel'],
    balcony: ['terrace', 'veranda', 'railing', 'patio', 'loggia', 'outdoor'],
    closet: ['wardrobe', 'cupboard', 'armoire', 'storage', 'dressing', 'cabinet'],
    sofa: ['couch', 'settee', 'lounge', 'seating', 'living-room', 'furniture'],
    furniture: ['furnishing', 'interior', 'home', 'fittings', 'decor', 'cabinet', 'table'],
};
