export const aliasesStatus: Record<string, string[]> = {
    active: ['status', 'online', 'enabled', 'running', 'live', 'on'],
    alarm: ['alert', 'bell', 'notification', 'reminder', 'clock', 'timer'],
    anomaly: ['warning', 'error', 'exception', 'unusual', 'irregular'],
    bullet: ['dot', 'list', 'marker', 'point', 'item', 'circle'],
    connected: ['linked', 'online', 'network', 'active', 'live'],
    defect: ['bug', 'fault', 'flaw', 'issue', 'damage', 'defective', 'broken', 'anomaly', 'incident', 'problem', 'crack', 'failure', 'snag'],
    dot: ['point', 'list', 'circle', 'item', 'marker'],
    empty: ['blank', 'null', 'void', 'nothing'],
    'gauge-high': ['meter', 'speed', 'fast', 'maximum', 'peak', 'limit', 'level-3', 'warning'],
    'gauge-low': ['meter', 'speed', 'slow', 'minimum', 'pressure', 'level-1', 'startup'],
    'gauge-medium': ['meter', 'speed', 'average', 'normal', 'balanced', 'level-2', 'steady'],
    inactive: ['status', 'offline', 'disabled', 'paused', 'off', 'idle'],
    minimum: ['basic', 'floor', 'lowest', 'limit', 'threshold', 'base', 'under'],
    'not-found': ['404', 'missing', 'error', 'lost', 'empty'],
    notice: ['alert', 'attention', 'important', 'announcement', 'info'],
    offline: ['disconnected', 'no-connection', 'unavailable'],
    online: ['connected', 'active', 'live', 'available'],
    'signal-full': ['wifi', 'network', 'strength', 'connection', 'bars'],
    'signal-low': ['wifi', 'network', 'weak', 'connection', 'bars'],
    'signal-medium': ['wifi', 'network', 'strength', 'connection', 'bars'],
    status: ['state', 'condition', 'info', 'indicator'],
    threshold: ['limit', 'boundary', 'trigger', 'level', 'maximum', 'minimum', 'range'],
    unassociated: ['unlinked', 'disconnected', 'separate', 'orphan'],
    wait: ['loading', 'pending', 'spinner', 'progress'],
    warning: ['alert', 'caution', 'danger', 'attention'],
};
