export const aliasesSymbols: Record<string, string[]> = {
    atom: ['physics', 'science', 'molecule', 'nuclear', 'chemistry', 'element'],
    badge: ['tag', 'label', 'sticker', 'id', 'credential', 'certificate', 'pass', 'card'],
    benefit: ['perk', 'reward', 'bonus', 'gift', 'advantage', 'value', 'included', 'offer'],
    burst: ['explosion', 'pop', 'energy', 'radiate', 'spark', 'blast'],
    certificate: ['award', 'diploma', 'credential', 'certification', 'degree', 'license', 'verified'],
    'crystal-globe': ['magic', 'future', 'fortune', 'prediction', 'glass'],
    cube: ['3d', 'box', 'shape', 'package', 'object', 'geometry'],
    death: ['grave', 'end', 'final', 'rip'],
    favorite: ['star', 'like', 'bookmark', 'love', 'heart'],
    ownership: ['owner', 'assigned', 'belongs', 'admin', 'administrator', 'responsible', 'author', 'creator', 'accountability', 'managed', 'assignee'],
    puzzle: ['game', 'logic', 'problem', 'piece'],
    'romania-flag': ['romania', 'romanian', 'flag', 'country', 'national', 'tricolor', 'europe'],
    rocket: ['launch', 'space', 'flight', 'project', 'start', 'mission', 'breakthrough'],
    sparkle: ['shine', 'star', 'magical', 'twinkle', 'glitter', 'special', 'bright', 'highlight'],
    star: ['astronomy', 'rating', 'celebrity', 'shining', 'cosmos'],
    target: ['goal', 'aim', 'focus', 'objective'],
    'theme-picker': ['colors', 'palette', 'appearance', 'style'],
};
