export const aliasesWeather: Record<string, string[]> = {
    cloud: ['upload', 'storage', 'sync', 'backup', 'online'],
    earth: ['globe', 'world', 'planet', 'global', 'international'],
    fire: ['hot', 'burn', 'danger', 'trending', 'flame'],
    fog: ['mist', 'haze', 'visibility', 'weather', 'atmosphere', 'cloud'],
    humidity: ['moisture', 'water', 'damp', 'weather'],
    leaf: ['nature', 'green', 'environment', 'eco'],
    moon: ['night', 'weather', 'dark', 'sleep', 'lunar'],
    outdoor: ['outside', 'external', 'weather', 'garden'],
    rain: ['weather', 'wet', 'water', 'storm'],
    rainbow: ['weather', 'nature', 'colorful', 'pride', 'hope'],
    saturn: ['planet', 'space', 'astronomy', 'universe'],
    seeds: ['plant', 'garden', 'growth', 'start'],
    snow: ['weather', 'cold', 'winter', 'freeze'],
    storm: ['thunder', 'lightning', 'weather', 'rain', 'electricity', 'cloud'],
    sun: ['weather', 'light', 'day', 'warmth', 'brightness'],
    tree: ['nature', 'forest', 'wood', 'outdoor'],
    wind: ['weather', 'air', 'breeze', 'storm'],
};
