export interface IconCategory {
    id: string;
    label: string;
    icons: string[];
}

export const OTHER_CATEGORY_ID = 'other';

export const iconCategoryDefinitions: IconCategory[] = [
    {
        id: 'navigation',
        label: 'Navigation & UI',
        icons: [
            'arrow-down',
            'arrow-left',
            'arrow-right',
            'arrow-up',
            'arrow-bidirectional-horizontal',
            'arrow-bidirectional-vertical',
            'brightness',
            'caret-down',
            'caret-left',
            'caret-right',
            'caret-up',
            'checkmark',
            'clear',
            'context',
            'deselect-all',
            'edit',
            'enlarge',
            'filters',
            'grid',
            'group',
            'layers',
            'list',
            'menu-hamburger',
            'minus',
            'next',
            'plus',
            'previous',
            'return',
            'search',
            'shrink',
            'square',
            'table',
            'toggle-off',
            'toggle-on',
            'tune',
            'ungroup',
            'vertical-dots',
            'view',
            'categories',
        ],
    },
    {
        id: 'status',
        label: 'Status & Indicators',
        icons: [
            'active',
            'alarm',
            'anomaly',
            'bullet',
            'connected',
            'defect',
            'dot',
            'empty',
            'gauge-high',
            'gauge-low',
            'gauge-medium',
            'inactive',
            'minimum',
            'notice',
            'offline',
            'online',
            'signal-full',
            'signal-low',
            'signal-medium',
            'status',
            'threshold',
            'unassociated',
            'wait',
            'warning',
            'not-found',
        ],
    },
    {
        id: 'time',
        label: 'Time & Calendar',
        icons: ['calendar', 'calendar-day', 'calendar-month', 'calendar-week', 'calendar-year', 'evening', 'history', 'morning', 'night', 'noon', 'time'],
    },
    {
        id: 'animals',
        label: 'Animals',
        icons: [
            'ant',
            'bat',
            'bear',
            'bee',
            'bug',
            'bunny',
            'butterfly',
            'cat',
            'caterpillar',
            'chicken',
            'cow',
            'dinosaur',
            'dog',
            'dolphin',
            'dragon',
            'duck',
            'elephant',
            'fish',
            'goat',
            'monkey',
            'mouse',
            'penguin',
            'pig',
            'snake',
            'turkey',
            'turtle',
        ],
    },
    {
        id: 'food',
        label: 'Food & Drink',
        icons: [
            'avocado',
            'banana',
            'beans',
            'beer',
            'birthday-cake',
            'blueberries',
            'bread',
            'breakfast',
            'cake',
            'candy',
            'carrot',
            'cheese',
            'cherries',
            'chestnut',
            'chocolate',
            'coffee',
            'cook',
            'cookies',
            'corn',
            'cucumber',
            'dessert',
            'dinner',
            'egg',
            'eggplant',
            'fondue',
            'food',
            'french-fries',
            'fruits',
            'glass',
            'ice-cream',
            'ingredients',
            'knife',
            'lemon',
            'lollipop',
            'lunch',
            'meat',
            'melon',
            'milk',
            'mushroom',
            'olives',
            'peanut',
            'pear',
            'pepper',
            'pizza',
            'polenta',
            'popcorn',
            'potato',
            'pudding',
            'rice',
            'salad',
            'salt',
            'soft-drink',
            'soup',
            'strawberry',
            'sugar',
            'tomato',
            'vegetables',
        ],
    },
    {
        id: 'nutrition',
        label: 'Nutrition',
        icons: ['carbs', 'fibers', 'glycemic-index', 'lipids', 'portions', 'proteins'],
    },
    {
        id: 'health',
        label: 'Health & Medical',
        icons: [
            'blood',
            'bones',
            'brain',
            'dental',
            'digestive',
            'doctor',
            'ears',
            'endocrine',
            'heart',
            'hospital',
            'laboratory',
            'liver',
            'lungs',
            'mental',
            'nervous',
            'nose',
            'pharmacy',
            'pill',
            'prescription',
            'referral',
            'reproductive',
            'skin',
            'skull',
            'surgery',
            'teeth',
            'stethoscope',
            'thermometer',
        ],
    },
    {
        id: 'weather',
        label: 'Weather & Nature',
        icons: [
            'cloud',
            'earth',
            'fire',
            'humidity',
            'leaf',
            'lightning',
            'moon',
            'outdoor',
            'rain',
            'rainbow',
            'saturn',
            'seeds',
            'fog',
            'snow',
            'storm',
            'sun',
            'tree',
            'wind',
        ],
    },
    {
        id: 'devices',
        label: 'Devices & IoT',
        icons: [
            'air-conditioning',
            'appliances',
            'button-device',
            'camera',
            'cpu',
            'devices',
            'digital',
            'dishwasher',
            'drying-machine',
            'fan',
            'fridge',
            'gas-detector',
            'gateway',
            'headphones',
            'ir-emitter',
            'joystick',
            'light-bulb',
            'light-switch',
            'microphone',
            'microwave',
            'monitor',
            'motion',
            'nas',
            'phone',
            'plug',
            'printer',
            'purifier',
            'raspberry',
            'robot',
            'router',
            'satellite',
            'smartphone',
            'smb',
            'smoke-detector',
            'speaker',
            'tv',
            'upnp',
            'vacuum',
            'washing-machine',
            'water-leak',
        ],
    },
    {
        id: 'transport',
        label: 'Transport & Travel',
        icons: ['bus', 'car', 'compass', 'location', 'map', 'mapping', 'pin', 'plane', 'ship', 'speedometer', 'taxi', 'train', 'transport-box', 'trip'],
    },
    {
        id: 'filetypes',
        label: 'File Types',
        icons: [
            'filetype-avi',
            'filetype-bat',
            'filetype-c',
            'filetype-css',
            'filetype-csv',
            'filetype-doc',
            'filetype-docx',
            'filetype-gif',
            'filetype-html',
            'filetype-ico',
            'filetype-ini',
            'filetype-javascript',
            'filetype-jpeg',
            'filetype-jpg',
            'filetype-json',
            'filetype-less',
            'filetype-mp3',
            'filetype-mp4',
            'filetype-mpg',
            'filetype-pdf',
            'filetype-php',
            'filetype-png',
            'filetype-ppt',
            'filetype-psd',
            'filetype-rar',
            'filetype-sass',
            'filetype-sql',
            'filetype-tiff',
            'filetype-txt',
            'filetype-typescript',
            'filetype-wav',
            'filetype-xls',
            'filetype-xlsx',
            'filetype-xml',
            'filetype-zip',
        ],
    },
    {
        id: 'files',
        label: 'Files & Storage',
        icons: [
            'archive',
            'backup',
            'clipboard',
            'document',
            'documents',
            'file',
            'folder',
            'folder-open',
            'memory',
            'save',
            'unarchive',
        ],
    },
    {
        id: 'communication',
        label: 'Communication',
        icons: ['announcement', 'bell', 'comment', 'language', 'mail'],
    },
    {
        id: 'people',
        label: 'People',
        icons: [
            'girl',
            'meet',
            'ninja',
            'old-person',
            'police',
            'police-man',
            'santa',
            'user',
            'users',
        ],
    },
    {
        id: 'sports',
        label: 'Sports & Activity',
        icons: ['ball', 'fishing-rod', 'hiking', 'pawn', 'running', 'scales', 'strength', 'trophy', 'workout', 'yoga'],
    },
    {
        id: 'holidays',
        label: 'Holidays & Celebrations',
        icons: ['balloon', 'bow', 'broken-heart', 'christmas-tree', 'confetti', 'fireworks', 'gift-box', 'handshake', 'pumpkin', 'snowman'],
    },
    {
        id: 'tools',
        label: 'Tools',
        icons: [
            'broom',
            'calibrate',
            'hammer',
            'ink-cartridge',
            'magnet',
            'microscope',
            'paint',
            'ruler',
            'scissors',
            'telescope',
            'toolbox',
            'wrench',
        ],
    },
    {
        id: 'security',
        label: 'Security',
        icons: ['firewall', 'gun', 'identity', 'incognito', 'key', 'lock', 'lock-open', 'security', 'shield', 'ssl'],
    },
    {
        id: 'network',
        label: 'Network & Web',
        icons: ['ajax', 'antenna', 'api', 'dns', 'external-link', 'link', 'network', 'wan', 'web', 'website-crawl', 'wifi'],
    },
    {
        id: 'analytics',
        label: 'Charts & Analytics',
        icons: ['analysis', 'chart', 'correlation', 'optimization', 'predictions', 'report', 'score', 'sequence', 'trend-down', 'trend-up'],
    },
    {
        id: 'media',
        label: 'Media',
        icons: [
            'cd-dvd',
            'equalizer',
            'gallery',
            'hd',
            'image',
            'movie',
            'musical-note',
            'mute',
            'pause',
            'play',
            'radio',
            'reload',
            'repeat',
            'sd',
            'shuffle',
            'stop',
            'stop-sign',
            'streaming',
            'theater',
            'unmute',
            'video',
            'youtube',
        ],
    },
    {
        id: 'places',
        label: 'Places & Buildings',
        icons: [
            'balcony',
            'bank',
            'basement',
            'bath',
            'bed',
            'building',
            'closet',
            'door',
            'furniture',
            'home',
            'lantern',
            'rooms',
            'school',
            'sofa',
        ],
    },
    {
        id: 'commerce',
        label: 'Commerce & Finance',
        icons: [
            'bill',
            'calculator',
            'credit-card',
            'expense',
            'insurance',
            'job',
            'money',
            'pension',
            'shopping-cart',
            'transactions',
        ],
    },
    {
        id: 'symbols',
        label: 'Symbols & Awards',
        icons: [
            'atom',
            'badge',
            'benefit',
            'burst',
            'certificate',
            'crystal-globe',
            'cube',
            'death',
            'favorite',
            'ownership',
            'puzzle',
            'romania-flag',
            'rocket',
            'sparkle',
            'star',
            'target',
            'theme-picker',
        ],
    },
    {
        id: 'astronomy',
        label: 'Astronomy & Space',
        icons: ['jupiter', 'mars', 'mercury', 'neptune', 'pluto', 'uranus', 'venus'],
    },
    {
        id: 'brands',
        label: 'Brands',
        icons: ['angular', 'github', 'linkedin', 'scss'],
    },
    {
        id: 'actions',
        label: 'Actions',
        icons: ['detach', 'download', 'duplicates', 'export', 'import', 'logout', 'manage', 'power', 'scan', 'settings', 'synchronize', 'upload'],
    },
    {
        id: 'misc',
        label: 'Miscellaneous',
        icons: ['book', 'briefcase', 'cigarette', 'dashboard', 'help', 'information', 'notes', 'other', 'reading', 'sources', 'staple', 'technical'],
    },
];

export const otherCategory: IconCategory = { id: OTHER_CATEGORY_ID, label: 'Other', icons: [] };

export const iconCategoryById = new Map(iconCategoryDefinitions.map(category => [category.id, category]));
iconCategoryById.set(OTHER_CATEGORY_ID, otherCategory);

export const iconCategoryByPath = new Map<string, string>();
iconCategoryDefinitions.forEach(category => {
    category.icons.forEach(filePath => {
        iconCategoryByPath.set(filePath, category.id);
    });
});
